### ISSUE TITLE
Art hero: Header is obstructing volume rocker

### ISSUE THREAD

**Issue by maslomeister** [Metagawa/Steam-Deck-Themes#17]
[This z-index is probably why](https://github.com/Metagawa/Steam-Deck-Themes/blob/56669c95cf0150d48c1d2353a35f79a0b7f7c6c0/Art%20Hero/shared.css#L127), i have no idea why it's set to 9999 and if it should be like that, but when you are on a home screen header is obsturcting volume rocker, it also breaks other plugins, for example Magic Black.

**Comment by Metagawa** [comment]
I don't support any random other theme/plugin so the magic black problem I'm not going to look into. As for the Z-index itself, been a while since I tweaked art hero at all but I believe that was set that way for the edge case of moving the header to the bottom of the screen. Feel free to remove that line in your own install for the time being to fix the issue while I put it through the submissions process.

**Comment by maslomeister** [comment]
Sorry for bumping this again, but after a bit of playing with CEF debugger, default z-index for header is 6000, after setting it in shared.css everything works fine.
